spring.application.name=microservice-spring-learn
server.port=8080
debug=true

spring.cloud.gateway.server.webflux.routes[0].id=example_route
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/example/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1